Extract methods
lilia-project/do_it_myself pull request #3
Opened 2021-03-19 10:48 UTC by lilia-project

2021-03-19 21:17 UTC, edvardino requested changes
Nice transformations! Read comments and try to do simple refactoring 👍

2021-03-19 21:17 UTC, edvardino commented on src/BaseConverter/BaseConverter.java
> +            methodConvert();
Good chunk for extraction!  Try to pick up appropriate name for the method. It is not clear what it does at the moment

2021-03-19 21:17 UTC, edvardino commented on src/BaseConverter/BaseConverter.java
> +            if (inputValidation(option)) return;
The same, it is a good part of code to extract to the separate method. But I would recommend using method name like isInvalidChoice(option) or invalidSelection(option). It becomes much simpler for understanding. You start reading a code like a book: if option - invalid selection then we do return. Accordingly, to conventions method name should be a verb but in the case of `if` construction and predicate (it is a method that returns a boolean value)

2021-03-20 13:07 UTC, lilia-project commented on src/BaseConverter/BaseConverter.java
> +            if (inputValidation(option)) return;
I fixed. 
Upload to the same branch?

2021-03-20 13:17 UTC, edvardino commented on src/BaseConverter/BaseConverter.java
> +            if (inputValidation(option)) return;
correct

2021-03-20 14:51 UTC, lilia-project commented on src/BaseConverter/BaseConverter.java
> +            if (inputValidation(option)) return;
I forgot files

2021-03-20 14:51 UTC, edvardino commented on src/BaseConverter/BaseConverter.java
> +            if (inputValidation(option)) return;
So, where are the changes?

2021-03-21 18:02 UTC, edvardino approved these changes
Do merge by yourself 💯

2021-03-21 18:09 UTC, merged